import { createServiceClient } from './service'
import type { SupabaseClient } from '@supabase/supabase-js'
import type { Database } from '@/types/database'

/**
 * Resolves a customer's canonical UUID from public.users (by email) and
 * returns a scoped Supabase client for customer-facing server pages.
 *
 * ── Why email, not session.user.id ──────────────────────────────────────────
 *
 * better-auth maintains its own 'user' table with TEXT IDs (e.g. "kmXht9Is…").
 * Our 'users' table uses UUID IDs generated by Postgres. These are different
 * values — session.user.id (better-auth ID) will never match public.users.id.
 * Email is the shared key between the two tables.
 *
 * ── Security model ──────────────────────────────────────────────────────────
 *
 * PRIMARY boundary (app-level):
 *   Every query MUST include an explicit .eq('customer_id', userId) filter
 *   where userId is the canonical UUID returned by this function.
 *
 * SECONDARY boundary (database-level):
 *   app.current_user_id is set to the canonical UUID so RLS policies on
 *   customer tables can enforce row-level isolation for direct DB access
 *   (Supabase dashboard, psql, any bypass of application code).
 *
 * ── Admin / staff pages ─────────────────────────────────────────────────────
 *
 *   Admin and staff pages use createServiceClient() directly — intentional,
 *   as they require cross-customer access. Never use this helper in admin routes.
 */
export async function createUserScopedClient(userEmail: string): Promise<{
  supabase: SupabaseClient<Database>
  userId: string
}> {
  const supabase = createServiceClient()

  // Resolve the canonical UUID from public.users by email.
  // This is necessary because better-auth uses its own 'user' table with
  // different IDs from our 'users' table.
  const { data: profile } = await supabase
    .from('users')
    .select('id')
    .eq('email', userEmail)
    .single()

  const userId = (profile as { id: string } | null)?.id ?? ''

  if (userId) {
    // Set app.current_user_id for DB-level RLS enforcement.
    // Non-fatal if it fails — the explicit .eq() filter is the primary guard.
    const { error } = await supabase.rpc('set_app_user_id', { user_id: userId })
    if (error) {
      console.warn('set_app_user_id failed (non-fatal):', error.message)
    }
  }

  return { supabase, userId }
}
